### PR TITLE
fix: Added the 2 relevant files for PR #59

### LINKED ISSUE #61: Extend process-badges.ts to generate badges.json
## Summary

In the previous task we crated scripts/auction_reconcillation/process-badges.ts
Let's add a few more lines to generate `badges.json` with the same format as `mint/badges.json`

### PR DESCRIPTION
**Pull request by Rcc999**
Closes #61 
Closes #59 

## Fixes for old PR

Had too many conflicts, so merged back from master to have less

## Summary by Sourcery

Add two scripts to automate auction winner badge processing and NFT metadata generation.

New Features:
- Introduce process_badges.ts to read bidder CSVs, clean and assign badges based on rank and bid counts, filter winners, and produce processed CSV and JSON outputs
- Introduce nft_metadata.ts to read processed badge data and generate a winners.json file with badge listings and top_21 position attributes

### CODE REVIEW

File: scripts/auction_reconcillation/process_badges.ts [hunk 1]
```diff
@@ -0,0 +1,185 @@
...
+			badges.add(Badge.last_bid);
+		}
+
+		if (bidder.rank > 0 && bidder.rank % 10 === 0) {
+			badges.add(Badge.every_10th_position);
+		}
+
+		if (bidder.rank > 0 && bidder.rank % 21 === 0) {
+			badges.add(Badge.nbtc_every_21st_bidder);
+		}
```
Comment (robert-zaremba) [inline scripts/auction_reconcillation/process_badges.ts:138]:
```suggestion
		if (bidder.rank === 5810) {
			badges.add(Badge.last_bid);
		}
		if (bidder.rank > 0 && (bidder.rank - 1) % 10 === 0) {
			badges.add(Badge.every_10th_position);
		}
		if (bidder.rank > 0 && (bidder.rank - 1) % 21 === 0) {
			badges.add(Badge.nbtc_every_21st_bidder);
		}
```

Comment (robert-zaremba) [reply scripts/auction_reconcillation/process_badges.ts:138]: rank starts from 1, so if we want to award the highest bidder with every_10 and every 21, then we should do `rank - 1`.

**Review by robert-zaremba — APPROVED** [review]
